EDGE_CREDIT="nxc@127.0.0.1"
PIPELINED=1
DIRNAME="debug"
TARGET_DNN_DIR="data/vgg16_base.aspen"
# TARGET_DNN_DIR="data/resnet50_base.aspen"
# TARGET_DNN_DIR="data/bert_base_base.aspen"
# TARGET_DNN_DIR="data/yolov3_base.aspen"
TARGET_NASM_DIR="data/vgg16_B8_T200.nasm"
# TARGET_NASM_DIR="data/resnet50_B8_T200.nasm"
# TARGET_NASM_DIR="data/bert_base_B1_T200.nasm"
# TARGET_NASM_DIR="data/yolov3_B1_T20.nasm"
TARGET_INPUT="data/batched_input_128.bin"
PREFIX="vgg16"
server_ip="127.0.0.1"
server_port=8100
# SCHEDULE_POLICY="local"
# SCHEDULE_POLICY="dynamic"
SCHEDULE_POLICY="conventional"
# SCHEDULE_POLICY="spinn"
DSE_NUM=64
OUTPUT_ORDER="cnn"
# OUTPUT_ORDER="transformer"
INFERENCE_REPEAT_NUM=10
NUM_EDGE_DEVICES=1
EDGE_DSE_NUM=32
